/* The emoji catalogue.
 *
 * Its own file because it is data, not behaviour: ~1300 lines of glyphs wedged
 * into the middle of app.js made the two functions that actually draw a picker
 * impossible to find, and every search for "emoji" in the codebase landed in
 * the middle of a list of vegetables.
 *
 * A classic script hanging off a global, the same as crypto.js and db.js —
 * there is no build step here, so a module would mean either a bundler or
 * `type="module"` and the ordering headaches that come with it, for a file that
 * is a single constant.
 *
 * Written as `'<glyph> <words>'` rather than `['<glyph>', '<words>']` because
 * a thousand entries of the second form is a thousand more quote marks to get
 * wrong, and the split is unambiguous: no emoji sequence contains U+0020. The
 * joiners inside 👨‍👩‍👦 and ❤️‍🔥 are U+200D, which is not a space.
 *
 * This is deliberately not the whole of Unicode. The full set is ~3,700 once
 * every skin tone, gender and regional variant is counted, and shipping all of
 * it to a two-person chat would cost more than the rest of the app put
 * together. What is here is what a picker actually gets used for; anything
 * missing can still be pasted in, because an emoji is only ever text.
 *
 * The names are what search matches on, so they carry the obvious synonyms
 * too — "lol" finds 😂 and "pray" finds 🙏, neither of which is the glyph's
 * Unicode name. Someone searching for a laughing face does not know or care
 * that it is officially "face with tears of joy".
 */
(function (root) {
  'use strict';

  /* [name, tab icon, entries]. Order is the order the tabs appear in, and
   * Reef leads because this app is named after it. */
  const GROUPS = [
    ['Reef', '🪸', [
      '🐟 fish',
      '🐠 tropical fish reef clownfish',
      '🐡 blowfish pufferfish',
      '🦈 shark',
      '🐙 octopus',
      '🦑 squid',
      '🦐 shrimp prawn',
      '🦞 lobster',
      '🦀 crab',
      '🐋 whale humpback',
      '🐳 spouting whale',
      '🐬 dolphin',
      '🦭 seal',
      '🐢 turtle tortoise',
      '🪼 jellyfish',
      '🪸 coral reef',
      '🐚 shell spiral conch',
      '🦪 oyster pearl',
      '🌊 wave ocean water sea',
      '🫧 bubbles',
      '💧 droplet water drop',
      '🏝️ desert island',
      '🏖️ beach umbrella sand',
      '⛵ sailboat sailing',
      '🚤 speedboat',
      '🛟 ring buoy lifesaver',
      '🤿 diving mask snorkel scuba',
      '🎣 fishing rod pole',
      '🪝 hook',
      '⚓ anchor',
      '🧭 compass',
      '🗺️ world map',
      '🦩 flamingo',
      '🐧 penguin',
      '🧜‍♀️ mermaid',
      '🧜‍♂️ merman',
      '🦦 otter',
      '🐊 crocodile alligator',
      '🏄 person surfing surf',
      '🏊 person swimming swim',
    ]],

    ['Smileys', '😀', [
      '😀 grinning face happy smile',
      '😃 grinning face big eyes happy',
      '😄 grinning face smiling eyes happy',
      '😁 beaming face grin',
      '😆 grinning squinting face laugh',
      '😅 grinning face sweat nervous laugh',
      '🤣 rolling on the floor laughing rofl',
      '😂 face with tears of joy lol laughing crying',
      '🙂 slightly smiling face',
      '🙃 upside down face silly sarcasm',
      '🫠 melting face',
      '😉 winking face wink',
      '😊 smiling face smiling eyes blush',
      '😇 smiling face with halo angel innocent',
      '🥰 smiling face with hearts love adore',
      '😍 smiling face heart eyes love',
      '🤩 star struck starry eyes amazed',
      '😘 face blowing a kiss',
      '😗 kissing face',
      '☺️ smiling face relaxed',
      '😚 kissing face closed eyes',
      '😙 kissing face smiling eyes',
      '🥲 smiling face with tear',
      '😋 face savoring food yum delicious',
      '😛 face with tongue',
      '😜 winking face with tongue cheeky',
      '🤪 zany face crazy goofy',
      '😝 squinting face with tongue',
      '🤑 money mouth face rich',
      '🤗 smiling face with open hands hug',
      '🤭 face with hand over mouth oops giggle',
      '🫢 face with open eyes and hand over mouth shock',
      '🫣 face with peeking eye peek',
      '🤫 shushing face quiet shh secret',
      '🤔 thinking face hmm think',
      '🫡 saluting face salute',
      '🤐 zipper mouth face',
      '🤨 face with raised eyebrow skeptical',
      '😐 neutral face',
      '😑 expressionless face',
      '😶 face without mouth speechless',
      '🫥 dotted line face invisible',
      '😶‍🌫️ face in clouds',
      '😏 smirking face smug',
      '😒 unamused face unimpressed',
      '🙄 face with rolling eyes eyeroll',
      '😬 grimacing face awkward yikes',
      '😮‍💨 face exhaling sigh relief',
      '🤥 lying face liar pinocchio',
      '🫨 shaking face shocked',
      '😌 relieved face calm content',
      '😔 pensive face sad',
      '😪 sleepy face tired',
      '🤤 drooling face',
      '😴 sleeping face asleep zzz',
      '😷 face with medical mask sick',
      '🤒 face with thermometer fever ill',
      '🤕 face with head bandage hurt injured',
      '🤢 nauseated face sick gross',
      '🤮 face vomiting puke',
      '🤧 sneezing face',
      '🥵 hot face sweating heat',
      '🥶 cold face freezing',
      '🥴 woozy face drunk',
      '😵 face with crossed out eyes knocked out',
      '😵‍💫 face with spiral eyes dizzy confused',
      '🤯 exploding head mind blown',
      '🤠 cowboy hat face',
      '🥳 partying face celebrate party',
      '🥸 disguised face',
      '😎 smiling face with sunglasses cool',
      '🤓 nerd face glasses geek',
      '🧐 face with monocle',
      '😕 confused face',
      '🫤 face with diagonal mouth meh',
      '😟 worried face',
      '🙁 slightly frowning face',
      '☹️ frowning face sad',
      '😮 face with open mouth wow surprised',
      '😯 hushed face surprised',
      '😲 astonished face shocked',
      '😳 flushed face embarrassed',
      '🥺 pleading face puppy eyes beg',
      '🥹 face holding back tears',
      '😦 frowning face with open mouth',
      '😧 anguished face',
      '😨 fearful face scared',
      '😰 anxious face with sweat',
      '😥 sad but relieved face',
      '😢 crying face tear sad',
      '😭 loudly crying face sobbing bawling',
      '😱 face screaming in fear scream',
      '😖 confounded face',
      '😣 persevering face',
      '😞 disappointed face',
      '😓 downcast face with sweat',
      '😩 weary face',
      '😫 tired face exhausted',
      '🥱 yawning face bored',
      '😤 face with steam from nose triumph huff',
      '😡 pouting face angry rage mad',
      '😠 angry face mad annoyed',
      '🤬 face with symbols on mouth cursing swearing',
      '😈 smiling face with horns devil mischief',
      '👿 angry face with horns imp',
      '💀 skull dead dying',
      '☠️ skull and crossbones poison',
      '💩 pile of poo crap',
      '🤡 clown face',
      '👹 ogre',
      '👺 goblin',
      '👻 ghost boo halloween',
      '👽 alien extraterrestrial',
      '👾 alien monster space invader',
      '🤖 robot bot',
      '😺 grinning cat',
      '😸 grinning cat smiling eyes',
      '😹 cat with tears of joy',
      '😻 smiling cat heart eyes',
      '😼 cat with wry smile',
      '😽 kissing cat',
      '🙀 weary cat shocked',
      '😿 crying cat',
      '😾 pouting cat',
      '🙈 see no evil monkey',
      '🙉 hear no evil monkey',
      '🙊 speak no evil monkey',
      '💋 kiss mark lips',
      '💌 love letter',
      '💘 heart with arrow cupid',
      '💝 heart with ribbon gift',
      '💖 sparkling heart',
      '💗 growing heart',
      '💓 beating heart',
      '💞 revolving hearts',
      '💕 two hearts',
      '💟 heart decoration',
      '❣️ heart exclamation',
      '💔 broken heart heartbreak',
      '❤️‍🔥 heart on fire burning',
      '❤️‍🩹 mending heart healing',
      '❤️ red heart love',
      '🩷 pink heart',
      '🧡 orange heart',
      '💛 yellow heart',
      '💚 green heart',
      '💙 blue heart',
      '🩵 light blue heart',
      '💜 purple heart',
      '🤎 brown heart',
      '🖤 black heart',
      '🩶 grey heart gray',
      '🤍 white heart',
      '💯 hundred points perfect score',
      '💢 anger symbol',
      '💥 collision boom explosion',
      '💫 dizzy stars',
      '💦 sweat droplets splash',
      '💨 dashing away wind fast',
      '🕳️ hole',
      '💬 speech balloon chat comment',
      '👁️‍🗨️ eye in speech bubble',
      '🗨️ left speech bubble',
      '🗯️ right anger bubble',
      '💭 thought balloon',
      '💤 zzz sleeping snore',
    ]],

    ['People', '👋', [
      '👋 waving hand hello bye wave',
      '🤚 raised back of hand',
      '🖐️ hand with fingers splayed',
      '✋ raised hand stop high five',
      '🖖 vulcan salute spock',
      '🫱 rightwards hand',
      '🫲 leftwards hand',
      '🫳 palm down hand',
      '🫴 palm up hand',
      '🫰 finger and thumb crossed money heart',
      '👌 ok hand',
      '🤌 pinched fingers italian',
      '🤏 pinching hand small tiny',
      '✌️ victory hand peace',
      '🤞 crossed fingers luck hope',
      '🤟 love you gesture',
      '🤘 sign of the horns rock',
      '🤙 call me hand shaka',
      '👈 backhand index pointing left',
      '👉 backhand index pointing right',
      '👆 backhand index pointing up',
      '🖕 middle finger',
      '👇 backhand index pointing down',
      '☝️ index pointing up',
      '🫵 index pointing at the viewer you',
      '👍 thumbs up like yes ok good',
      '👎 thumbs down dislike no bad',
      '✊ raised fist',
      '👊 oncoming fist punch fist bump',
      '🤛 left facing fist',
      '🤜 right facing fist',
      '👏 clapping hands applause clap',
      '🙌 raising hands celebration praise',
      '🫶 heart hands love',
      '👐 open hands',
      '🤲 palms up together',
      '🤝 handshake deal agreement',
      '🙏 folded hands please thanks pray namaste',
      '✍️ writing hand',
      '💅 nail polish manicure',
      '🤳 selfie',
      '💪 flexed biceps strong muscle',
      '🦾 mechanical arm prosthetic',
      '🦿 mechanical leg prosthetic',
      '🦵 leg',
      '🦶 foot',
      '👂 ear',
      '🦻 ear with hearing aid',
      '👃 nose',
      '🧠 brain',
      '🫀 anatomical heart',
      '🫁 lungs',
      '🦷 tooth',
      '🦴 bone',
      '👀 eyes looking',
      '👁️ eye',
      '👅 tongue',
      '👄 mouth lips',
      '🫦 biting lip',
      '👶 baby infant',
      '🧒 child',
      '👦 boy',
      '👧 girl',
      '🧑 person adult',
      '👱 person blond hair',
      '👨 man',
      '🧔 person beard',
      '👩 woman',
      '🧓 older person',
      '👴 old man grandpa',
      '👵 old woman grandma',
      '🙍 person frowning',
      '🙎 person pouting',
      '🙅 person gesturing no',
      '🙆 person gesturing ok',
      '💁 person tipping hand sassy info',
      '🙋 person raising hand question',
      '🧏 deaf person',
      '🙇 person bowing sorry apology',
      '🤦 person facepalming facepalm',
      '🤷 person shrugging shrug',
      '👮 police officer cop',
      '🕵️ detective spy',
      '💂 guard',
      '🥷 ninja',
      '👷 construction worker builder',
      '🫅 person with crown royalty',
      '🤴 prince',
      '👸 princess',
      '👳 person wearing turban',
      '👲 person with skullcap',
      '🧕 woman with headscarf hijab',
      '🤵 person in tuxedo groom',
      '👰 person with veil bride wedding',
      '🤰 pregnant woman',
      '🫃 pregnant man',
      '🤱 breast feeding',
      '👼 baby angel cherub',
      '🎅 santa claus christmas',
      '🤶 mrs claus christmas',
      '🦸 superhero hero',
      '🦹 supervillain villain',
      '🧙 mage wizard',
      '🧚 fairy',
      '🧛 vampire',
      '🧜 merperson',
      '🧝 elf',
      '🧞 genie',
      '🧟 zombie',
      '🧌 troll',
      '💆 person getting massage spa',
      '💇 person getting haircut salon',
      '🚶 person walking walk',
      '🧍 person standing',
      '🧎 person kneeling',
      '🏃 person running run',
      '💃 woman dancing dance',
      '🕺 man dancing dance',
      '🕴️ person in suit levitating',
      '👯 people with bunny ears party',
      '🧖 person in steamy room sauna',
      '🧗 person climbing',
      '🧘 person in lotus position yoga meditate',
      '🛀 person taking bath',
      '🛌 person in bed sleeping',
      '👭 women holding hands',
      '👫 woman and man holding hands couple',
      '👬 men holding hands',
      '🧑‍🤝‍🧑 people holding hands friends',
      '💏 kiss couple',
      '💑 couple with heart',
      '👪 family',
      '🗣️ speaking head talking',
      '👤 bust in silhouette person',
      '👥 busts in silhouette people',
      '🫂 people hugging hug',
      '👣 footprints',
      '🧑‍💻 technologist coder developer',
      '🧑‍🍳 cook chef',
      '🧑‍🏫 teacher',
      '🧑‍⚕️ health worker doctor nurse',
      '🧑‍🚀 astronaut',
      '🧑‍🚒 firefighter',
      '🧑‍🌾 farmer',
      '🧑‍🔧 mechanic',
      '🧑‍🎤 singer rockstar',
      '🧑‍🎨 artist painter',
      '🧑‍⚖️ judge',
      '🧑‍✈️ pilot',
      '🧑‍🎓 student graduate',
      '🧑‍🏭 factory worker',
      '🧑‍💼 office worker',
      '🧑‍🔬 scientist',
    ]],

    ['Nature', '🐶', [
      '🐶 dog face puppy',
      '🐱 cat face kitty',
      '🐭 mouse face',
      '🐹 hamster',
      '🐰 rabbit face bunny',
      '🦊 fox',
      '🐻 bear',
      '🐼 panda',
      '🐻‍❄️ polar bear',
      '🐨 koala',
      '🐯 tiger face',
      '🦁 lion',
      '🐮 cow face',
      '🐷 pig face',
      '🐽 pig nose',
      '🐸 frog',
      '🐵 monkey face',
      '🐒 monkey',
      '🦍 gorilla',
      '🦧 orangutan',
      '🐔 chicken hen',
      '🐦 bird',
      '🐤 baby chick',
      '🐣 hatching chick',
      '🐥 front facing baby chick',
      '🦆 duck',
      '🦢 swan',
      '🦅 eagle',
      '🦉 owl',
      '🦇 bat',
      '🐺 wolf',
      '🐗 boar',
      '🐴 horse face',
      '🦄 unicorn',
      '🐝 honeybee bee',
      '🪱 worm',
      '🐛 bug caterpillar',
      '🦋 butterfly',
      '🐌 snail',
      '🐞 lady beetle ladybug',
      '🐜 ant',
      '🪰 fly',
      '🪲 beetle',
      '🪳 cockroach',
      '🦟 mosquito',
      '🦗 cricket',
      '🕷️ spider',
      '🕸️ spider web cobweb',
      '🦂 scorpion',
      '🐍 snake',
      '🦎 lizard gecko',
      '🦖 t rex dinosaur',
      '🦕 sauropod dinosaur',
      '🐅 tiger',
      '🐆 leopard',
      '🦓 zebra',
      '🦣 mammoth',
      '🐘 elephant',
      '🦛 hippopotamus hippo',
      '🦏 rhinoceros rhino',
      '🐪 camel',
      '🐫 two hump camel',
      '🦒 giraffe',
      '🦘 kangaroo',
      '🦬 bison',
      '🐃 water buffalo',
      '🐂 ox',
      '🐄 cow',
      '🐎 horse racing',
      '🐖 pig',
      '🐏 ram',
      '🐑 ewe sheep',
      '🦙 llama alpaca',
      '🐐 goat',
      '🦌 deer',
      '🐕 dog',
      '🐩 poodle',
      '🦮 guide dog',
      '🐕‍🦺 service dog',
      '🐈 cat',
      '🐈‍⬛ black cat',
      '🪶 feather',
      '🐓 rooster',
      '🦃 turkey',
      '🦤 dodo',
      '🦚 peacock',
      '🦜 parrot',
      '🕊️ dove peace bird',
      '🐇 rabbit',
      '🦝 raccoon',
      '🦨 skunk',
      '🦡 badger',
      '🦫 beaver',
      '🦥 sloth',
      '🐁 mouse',
      '🐀 rat',
      '🐿️ chipmunk squirrel',
      '🦔 hedgehog',
      '🐾 paw prints',
      '🐉 dragon',
      '🐲 dragon face',
      '🌵 cactus',
      '🎄 christmas tree',
      '🌲 evergreen tree',
      '🌳 deciduous tree',
      '🌴 palm tree',
      '🪵 wood log',
      '🌱 seedling sprout',
      '🌿 herb plant',
      '☘️ shamrock',
      '🍀 four leaf clover luck',
      '🎍 pine decoration',
      '🪴 potted plant',
      '🎋 tanabata tree',
      '🍃 leaf fluttering in wind',
      '🍂 fallen leaf autumn',
      '🍁 maple leaf',
      '🍄 mushroom',
      '🪨 rock stone',
      '🌾 sheaf of rice wheat',
      '💐 bouquet flowers',
      '🌷 tulip',
      '🌹 rose',
      '🥀 wilted flower',
      '🌺 hibiscus',
      '🌸 cherry blossom sakura flower',
      '🌼 blossom flower',
      '🌻 sunflower',
      '🌞 sun with face',
      '🌝 full moon face',
      '🌛 first quarter moon face',
      '🌜 last quarter moon face',
      '🌚 new moon face',
      '🌕 full moon',
      '🌖 waning gibbous moon',
      '🌗 last quarter moon',
      '🌘 waning crescent moon',
      '🌑 new moon',
      '🌒 waxing crescent moon',
      '🌓 first quarter moon',
      '🌔 waxing gibbous moon',
      '🌙 crescent moon night',
      '🌎 globe americas earth world',
      '🌍 globe europe africa earth world',
      '🌏 globe asia australia earth world',
      '🪐 ringed planet saturn',
      '⭐ star',
      '🌟 glowing star',
      '✨ sparkles shiny magic',
      '⚡ high voltage lightning zap',
      '☄️ comet',
      '🔥 fire lit flame hot',
      '🌪️ tornado',
      '🌈 rainbow',
      '☀️ sun sunny',
      '🌤️ sun behind small cloud',
      '⛅ sun behind cloud',
      '🌥️ sun behind large cloud',
      '☁️ cloud cloudy',
      '🌦️ sun behind rain cloud',
      '🌧️ cloud with rain rainy',
      '⛈️ cloud with lightning and rain storm',
      '🌩️ cloud with lightning thunder',
      '🌨️ cloud with snow',
      '❄️ snowflake snow cold',
      '☃️ snowman',
      '⛄ snowman without snow',
      '🌬️ wind face blowing',
      '☔ umbrella with rain drops',
      '☂️ umbrella',
      '🌫️ fog foggy mist',
    ]],

    ['Food', '🍕', [
      '🍏 green apple',
      '🍎 red apple',
      '🍐 pear',
      '🍊 tangerine orange',
      '🍋 lemon',
      '🍌 banana',
      '🍉 watermelon',
      '🍇 grapes',
      '🍓 strawberry',
      '🫐 blueberries',
      '🍈 melon',
      '🍒 cherries',
      '🍑 peach',
      '🥭 mango',
      '🍍 pineapple',
      '🥥 coconut',
      '🥝 kiwi fruit',
      '🍅 tomato',
      '🍆 aubergine eggplant',
      '🥑 avocado',
      '🥦 broccoli',
      '🥬 leafy green lettuce',
      '🥒 cucumber',
      '🌶️ hot pepper chilli spicy',
      '🫑 bell pepper capsicum',
      '🌽 corn maize',
      '🥕 carrot',
      '🫒 olive',
      '🧄 garlic',
      '🧅 onion',
      '🥔 potato',
      '🍠 roasted sweet potato',
      '🫘 beans',
      '🥐 croissant',
      '🥯 bagel',
      '🍞 bread loaf',
      '🥖 baguette bread',
      '🥨 pretzel',
      '🧀 cheese',
      '🥚 egg',
      '🍳 cooking fried egg',
      '🧈 butter',
      '🥞 pancakes',
      '🧇 waffle',
      '🥓 bacon',
      '🥩 cut of meat steak',
      '🍗 poultry leg chicken drumstick',
      '🍖 meat on bone',
      '🦴 bone',
      '🌭 hot dog',
      '🍔 hamburger burger',
      '🍟 french fries chips',
      '🍕 pizza',
      '🫓 flatbread roti naan',
      '🥪 sandwich',
      '🥙 stuffed flatbread kebab',
      '🧆 falafel',
      '🌮 taco',
      '🌯 burrito',
      '🫔 tamale',
      '🥗 green salad',
      '🥘 shallow pan of food curry',
      '🫕 fondue',
      '🥫 canned food',
      '🍝 spaghetti pasta noodles',
      '🍜 steaming bowl ramen noodles',
      '🍲 pot of food stew',
      '🍛 curry rice',
      '🍣 sushi',
      '🍱 bento box',
      '🥟 dumpling momo',
      '🍤 fried shrimp tempura',
      '🍙 rice ball onigiri',
      '🍚 cooked rice',
      '🍘 rice cracker',
      '🍥 fish cake',
      '🥠 fortune cookie',
      '🥮 moon cake',
      '🍢 oden skewer',
      '🍡 dango',
      '🍧 shaved ice',
      '🍨 ice cream',
      '🍦 soft ice cream cone',
      '🥧 pie',
      '🧁 cupcake',
      '🍰 shortcake slice of cake',
      '🎂 birthday cake',
      '🍮 custard flan pudding',
      '🍭 lollipop',
      '🍬 candy sweet',
      '🍫 chocolate bar',
      '🍿 popcorn',
      '🍩 doughnut donut',
      '🍪 cookie biscuit',
      '🌰 chestnut',
      '🥜 peanuts nuts',
      '🍯 honey pot',
      '🥛 glass of milk',
      '🍼 baby bottle',
      '🫖 teapot chai',
      '☕ hot beverage coffee tea',
      '🍵 teacup without handle green tea',
      '🧃 beverage box juice',
      '🥤 cup with straw soda',
      '🧋 bubble tea boba',
      '🍶 sake',
      '🍺 beer mug',
      '🍻 clinking beer mugs cheers',
      '🥂 clinking glasses cheers champagne',
      '🍷 wine glass',
      '🥃 tumbler glass whisky',
      '🍸 cocktail glass martini',
      '🍹 tropical drink',
      '🧉 mate',
      '🍾 bottle with popping cork champagne',
      '🧊 ice cube',
      '🥄 spoon',
      '🍴 fork and knife',
      '🍽️ fork and knife with plate dinner',
      '🥣 bowl with spoon cereal',
      '🥡 takeout box',
      '🥢 chopsticks',
      '🧂 salt',
    ]],

    ['Activity', '⚽', [
      '⚽ soccer ball football',
      '🏀 basketball',
      '🏈 american football',
      '⚾ baseball',
      '🥎 softball',
      '🎾 tennis',
      '🏐 volleyball',
      '🏉 rugby football',
      '🥏 flying disc frisbee',
      '🎱 pool 8 ball billiards',
      '🪀 yo yo',
      '🏓 ping pong table tennis',
      '🏸 badminton',
      '🏒 ice hockey',
      '🏑 field hockey',
      '🥍 lacrosse',
      '🏏 cricket game bat',
      '🪃 boomerang',
      '🥅 goal net',
      '⛳ flag in hole golf',
      '🪁 kite',
      '🏹 bow and arrow archery',
      '🥊 boxing glove',
      '🥋 martial arts uniform karate',
      '🎽 running shirt',
      '🛹 skateboard',
      '🛼 roller skate',
      '🛷 sled',
      '⛸️ ice skate',
      '🥌 curling stone',
      '🎿 skis',
      '⛷️ skier',
      '🏂 snowboarder',
      '🪂 parachute',
      '🏋️ person lifting weights gym',
      '🤼 people wrestling',
      '🤸 person cartwheeling',
      '⛹️ person bouncing ball',
      '🤺 person fencing',
      '🤾 person playing handball',
      '🏌️ person golfing',
      '🏇 horse racing jockey',
      '🚣 person rowing boat',
      '🧗 person climbing',
      '🚵 person mountain biking',
      '🚴 person biking cycling',
      '🤽 person playing water polo',
      '🏆 trophy winner',
      '🥇 1st place medal gold',
      '🥈 2nd place medal silver',
      '🥉 3rd place medal bronze',
      '🏅 sports medal',
      '🎖️ military medal',
      '🏵️ rosette',
      '🎗️ reminder ribbon',
      '🎫 ticket',
      '🎟️ admission tickets',
      '🎪 circus tent',
      '🤹 person juggling',
      '🎭 performing arts theatre masks',
      '🩰 ballet shoes',
      '🎨 artist palette painting',
      '🎬 clapper board film movie',
      '🎤 microphone singing karaoke',
      '🎧 headphone music',
      '🎼 musical score',
      '🎵 musical note music',
      '🎶 musical notes music',
      '🎹 musical keyboard piano',
      '🥁 drum',
      '🪘 long drum tabla',
      '🎷 saxophone',
      '🎺 trumpet',
      '🪗 accordion',
      '🎸 guitar',
      '🪕 banjo',
      '🎻 violin',
      '🎲 game die dice',
      '♟️ chess pawn',
      '🎯 bullseye dart target',
      '🎳 bowling',
      '🎮 video game controller',
      '🕹️ joystick',
      '🎰 slot machine',
      '🧩 puzzle piece jigsaw',
      '🧸 teddy bear',
      '🪅 pinata',
      '🪆 nesting dolls',
      '🎊 confetti ball',
      '🎉 party popper celebration congrats',
      '🎈 balloon',
      '🎁 wrapped gift present',
      '🎀 ribbon bow',
      '🪩 mirror ball disco',
      '🧨 firecracker',
      '🎇 sparkler',
      '🎆 fireworks',
      '🎃 jack o lantern halloween pumpkin',
      '🎏 carp streamer',
      '🎐 wind chime',
      '🎎 japanese dolls',
      '🏮 red paper lantern',
      '🧧 red envelope',
      '🪄 magic wand',
    ]],

    ['Travel', '✈️', [
      '🚗 car automobile',
      '🚕 taxi cab',
      '🚙 sport utility vehicle suv',
      '🚌 bus',
      '🚎 trolleybus',
      '🏎️ racing car',
      '🚓 police car',
      '🚑 ambulance',
      '🚒 fire engine',
      '🚐 minibus van',
      '🛻 pickup truck',
      '🚚 delivery truck',
      '🚛 articulated lorry truck',
      '🚜 tractor',
      '🦯 white cane',
      '🦽 manual wheelchair',
      '🦼 motorized wheelchair',
      '🛴 kick scooter',
      '🚲 bicycle bike cycle',
      '🛵 motor scooter scooty',
      '🏍️ motorcycle bike',
      '🛺 auto rickshaw tuktuk',
      '🚨 police car light siren',
      '🚔 oncoming police car',
      '🚍 oncoming bus',
      '🚘 oncoming automobile',
      '🚖 oncoming taxi',
      '🛞 wheel tyre',
      '🚡 aerial tramway',
      '🚠 mountain cableway',
      '🚟 suspension railway',
      '🚃 railway car',
      '🚋 tram car',
      '🚞 mountain railway',
      '🚝 monorail',
      '🚄 high speed train',
      '🚅 bullet train',
      '🚈 light rail',
      '🚂 locomotive steam train',
      '🚆 train',
      '🚇 metro subway',
      '🚊 tram',
      '🚉 station',
      '✈️ airplane plane flight',
      '🛫 airplane departure takeoff',
      '🛬 airplane arrival landing',
      '🛩️ small airplane',
      '💺 seat',
      '🛰️ satellite',
      '🚀 rocket launch space',
      '🛸 flying saucer ufo',
      '🚁 helicopter',
      '🛶 canoe kayak',
      '⛵ sailboat',
      '🚤 speedboat',
      '🛥️ motor boat',
      '🛳️ passenger ship cruise',
      '⛴️ ferry',
      '🚢 ship',
      '⚓ anchor',
      '⛽ fuel pump petrol gas',
      '🚧 construction barrier roadworks',
      '🚦 vertical traffic light',
      '🚥 horizontal traffic light',
      '🚏 bus stop',
      '🗺️ world map',
      '🗿 moai statue',
      '🗽 statue of liberty',
      '🗼 tokyo tower',
      '🏰 castle',
      '🏯 japanese castle',
      '🏟️ stadium',
      '🎡 ferris wheel',
      '🎢 roller coaster',
      '🎠 carousel horse',
      '⛲ fountain',
      '⛱️ umbrella on ground beach',
      '🏖️ beach with umbrella',
      '🏝️ desert island',
      '🏜️ desert',
      '🌋 volcano',
      '⛰️ mountain',
      '🏔️ snow capped mountain',
      '🗻 mount fuji',
      '🏕️ camping',
      '⛺ tent',
      '🛖 hut',
      '🏠 house home',
      '🏡 house with garden',
      '🏘️ houses',
      '🏚️ derelict house',
      '🏗️ building construction',
      '🏭 factory',
      '🏢 office building',
      '🏬 department store',
      '🏣 japanese post office',
      '🏤 post office',
      '🏥 hospital',
      '🏦 bank',
      '🏨 hotel',
      '🏪 convenience store',
      '🏫 school',
      '🏩 love hotel',
      '💒 wedding',
      '🏛️ classical building',
      '⛪ church',
      '🕌 mosque',
      '🕍 synagogue',
      '🛕 hindu temple mandir',
      '🕋 kaaba',
      '⛩️ shinto shrine',
      '🛤️ railway track',
      '🛣️ motorway highway road',
      '🗾 map of japan',
      '🎑 moon viewing ceremony',
      '🏞️ national park',
      '🌅 sunrise',
      '🌄 sunrise over mountains',
      '🌠 shooting star',
      '🌇 sunset',
      '🌆 cityscape at dusk',
      '🏙️ cityscape skyline',
      '🌃 night with stars',
      '🌌 milky way',
      '🌉 bridge at night',
      '🌁 foggy',
      '🧳 luggage suitcase travel',
      '🎒 backpack',
      '🛎️ bellhop bell hotel',
      '🛂 passport control',
      '🛃 customs',
      '🛄 baggage claim',
      '🛅 left luggage',
    ]],

    ['Objects', '💡', [
      '⌚ watch',
      '📱 mobile phone smartphone',
      '📲 mobile phone with arrow',
      '💻 laptop computer',
      '⌨️ keyboard',
      '🖥️ desktop computer',
      '🖨️ printer',
      '🖱️ computer mouse',
      '🖲️ trackball',
      '💽 computer disk',
      '💾 floppy disk save',
      '💿 optical disk cd',
      '📀 dvd',
      '📼 videocassette',
      '📷 camera',
      '📸 camera with flash',
      '📹 video camera',
      '🎥 movie camera',
      '📽️ film projector',
      '🎞️ film frames',
      '📞 telephone receiver call',
      '☎️ telephone',
      '📟 pager',
      '📠 fax machine',
      '📺 television tv',
      '📻 radio',
      '🎙️ studio microphone podcast',
      '🎚️ level slider',
      '🎛️ control knobs',
      '⏱️ stopwatch',
      '⏲️ timer clock',
      '⏰ alarm clock',
      '🕰️ mantelpiece clock',
      '⌛ hourglass done',
      '⏳ hourglass not done waiting',
      '📡 satellite antenna',
      '🔋 battery',
      '🪫 low battery',
      '🔌 electric plug',
      '💡 light bulb idea',
      '🔦 flashlight torch',
      '🕯️ candle',
      '🪔 diya lamp diwali',
      '🧯 fire extinguisher',
      '🛢️ oil drum',
      '💸 money with wings',
      '💵 dollar banknote money',
      '💴 yen banknote',
      '💶 euro banknote',
      '💷 pound banknote',
      '🪙 coin',
      '💰 money bag',
      '💳 credit card',
      '🪪 identification card',
      '💎 gem stone diamond',
      '⚖️ balance scale justice',
      '🪜 ladder',
      '🧰 toolbox',
      '🪛 screwdriver',
      '🔧 wrench spanner',
      '🔨 hammer',
      '⚒️ hammer and pick',
      '🛠️ hammer and wrench tools',
      '⛏️ pick',
      '🪚 carpentry saw',
      '🔩 nut and bolt',
      '⚙️ gear settings cog',
      '🪤 mouse trap',
      '🧱 brick',
      '⛓️ chains',
      '🧲 magnet',
      '🔫 water pistol gun',
      '💣 bomb',
      '🧨 firecracker dynamite',
      '🪓 axe',
      '🔪 kitchen knife',
      '🗡️ dagger',
      '⚔️ crossed swords',
      '🛡️ shield',
      '🚬 cigarette smoking',
      '⚰️ coffin',
      '🪦 headstone grave',
      '⚱️ funeral urn',
      '🏺 amphora',
      '🔮 crystal ball fortune',
      '📿 prayer beads mala',
      '🧿 nazar amulet evil eye',
      '🪬 hamsa',
      '💈 barber pole',
      '⚗️ alembic chemistry',
      '🔭 telescope',
      '🔬 microscope',
      '🩻 x ray',
      '🩹 adhesive bandage plaster',
      '🩺 stethoscope',
      '💊 pill medicine',
      '💉 syringe injection vaccine',
      '🩸 drop of blood',
      '🧬 dna',
      '🦠 microbe virus germ',
      '🧫 petri dish',
      '🧪 test tube',
      '🌡️ thermometer',
      '🧹 broom',
      '🪠 plunger',
      '🧺 basket laundry',
      '🧻 roll of paper toilet',
      '🚽 toilet',
      '🚰 potable water tap',
      '🚿 shower',
      '🛁 bathtub',
      '🧼 soap',
      '🪥 toothbrush',
      '🪒 razor',
      '🧽 sponge',
      '🪣 bucket',
      '🧴 lotion bottle',
      '🔑 key',
      '🗝️ old key',
      '🚪 door',
      '🪑 chair',
      '🛋️ couch and lamp sofa',
      '🛏️ bed',
      '🖼️ framed picture',
      '🪞 mirror',
      '🪟 window',
      '🛍️ shopping bags',
      '🛒 shopping cart trolley',
      '✉️ envelope mail email',
      '📩 envelope with arrow',
      '📨 incoming envelope',
      '📧 e mail',
      '📥 inbox tray',
      '📤 outbox tray',
      '📦 package parcel box',
      '🏷️ label tag',
      '🪧 placard sign',
      '📪 closed mailbox lowered flag',
      '📫 closed mailbox raised flag',
      '📬 open mailbox raised flag',
      '📭 open mailbox lowered flag',
      '📮 postbox',
      '📜 scroll',
      '📃 page with curl',
      '📄 page facing up document',
      '📑 bookmark tabs',
      '🧾 receipt',
      '📊 bar chart',
      '📈 chart increasing growth',
      '📉 chart decreasing',
      '🗒️ spiral notepad notes',
      '🗓️ spiral calendar',
      '📆 tear off calendar',
      '📅 calendar date',
      '🗑️ wastebasket bin trash delete',
      '📇 card index',
      '🗃️ card file box',
      '🗳️ ballot box vote',
      '🗄️ file cabinet',
      '📋 clipboard',
      '📁 file folder',
      '📂 open file folder',
      '🗂️ card index dividers',
      '🗞️ rolled up newspaper',
      '📰 newspaper news',
      '📓 notebook',
      '📔 notebook with decorative cover',
      '📒 ledger',
      '📕 closed book',
      '📗 green book',
      '📘 blue book',
      '📙 orange book',
      '📚 books library',
      '📖 open book reading',
      '🔖 bookmark',
      '🧷 safety pin',
      '🔗 link chain url',
      '📎 paperclip attach',
      '🖇️ linked paperclips',
      '📐 triangular ruler',
      '📏 straight ruler',
      '🧮 abacus',
      '📌 pushpin pin',
      '📍 round pushpin location',
      '✂️ scissors cut',
      '🖊️ pen',
      '🖋️ fountain pen',
      '✒️ black nib',
      '🖌️ paintbrush',
      '🖍️ crayon',
      '📝 memo writing note',
      '✏️ pencil',
      '🔍 magnifying glass tilted left search',
      '🔎 magnifying glass tilted right search',
      '🔏 locked with pen',
      '🔐 locked with key',
      '🔒 locked lock secure private',
      '🔓 unlocked',
      '👓 glasses spectacles',
      '🕶️ sunglasses',
      '🥽 goggles',
      '🥼 lab coat',
      '🦺 safety vest',
      '👔 necktie',
      '👕 t shirt tshirt',
      '👖 jeans trousers',
      '🧣 scarf',
      '🧤 gloves',
      '🧥 coat',
      '🧦 socks',
      '👗 dress',
      '👘 kimono',
      '🥻 sari saree',
      '🩱 one piece swimsuit',
      '🩲 briefs',
      '🩳 shorts',
      '👙 bikini',
      '👚 woman clothes blouse',
      '👛 purse',
      '👜 handbag',
      '👝 clutch bag',
      '🎒 backpack school bag',
      '👞 man shoe',
      '👟 running shoe sneaker',
      '🥾 hiking boot',
      '🥿 flat shoe',
      '👠 high heeled shoe',
      '👡 sandal',
      '🩴 thong sandal flip flop chappal',
      '👢 boot',
      '👑 crown king queen',
      '👒 woman hat',
      '🎩 top hat',
      '🎓 graduation cap',
      '🧢 billed cap',
      '🪖 military helmet',
      '⛑️ rescue worker helmet',
      '💄 lipstick',
      '💍 ring engagement',
      '📢 loudspeaker announcement',
      '📣 megaphone cheering',
      '🔔 bell notification',
      '🔕 bell with slash muted',
    ]],

    ['Symbols', '🔣', [
      '✅ check mark button done yes',
      '☑️ check box with check',
      '✔️ check mark tick',
      '❌ cross mark no wrong',
      '❎ cross mark button',
      '❓ question mark',
      '❔ white question mark',
      '❗ exclamation mark',
      '❕ white exclamation mark',
      '‼️ double exclamation mark',
      '⁉️ exclamation question mark',
      '⭕ hollow red circle',
      '🚫 prohibited no forbidden',
      '⛔ no entry',
      '📵 no mobile phones',
      '🚭 no smoking',
      '🔞 no one under eighteen',
      '☢️ radioactive',
      '☣️ biohazard',
      '⚠️ warning caution',
      '🚸 children crossing',
      '♻️ recycling symbol recycle',
      '⚕️ medical symbol',
      '🈯 reserved',
      '💹 chart increasing with yen',
      '❇️ sparkle',
      '✳️ eight spoked asterisk',
      '✴️ eight pointed star',
      '➕ plus',
      '➖ minus',
      '➗ divide',
      '✖️ multiply',
      '🟰 heavy equals sign',
      '♾️ infinity',
      '〰️ wavy dash',
      '➰ curly loop',
      '➿ double curly loop',
      '💲 heavy dollar sign',
      '💱 currency exchange',
      '™️ trade mark',
      '©️ copyright',
      '®️ registered',
      '🔚 end arrow',
      '🔙 back arrow',
      '🔛 on arrow',
      '🔝 top arrow',
      '🔜 soon arrow',
      '▶️ play button',
      '⏸️ pause button',
      '⏯️ play or pause button',
      '⏹️ stop button',
      '⏺️ record button',
      '⏭️ next track button',
      '⏮️ last track button',
      '⏩ fast forward',
      '⏪ fast reverse',
      '⏫ fast up button',
      '⏬ fast down button',
      '◀️ reverse button',
      '🔼 upwards button',
      '🔽 downwards button',
      '➡️ right arrow',
      '⬅️ left arrow',
      '⬆️ up arrow',
      '⬇️ down arrow',
      '↗️ up right arrow',
      '↘️ down right arrow',
      '↙️ down left arrow',
      '↖️ up left arrow',
      '↕️ up down arrow',
      '↔️ left right arrow',
      '↩️ right arrow curving left reply',
      '↪️ left arrow curving right forward',
      '⤴️ right arrow curving up',
      '⤵️ right arrow curving down',
      '🔀 shuffle tracks button',
      '🔁 repeat button loop',
      '🔂 repeat single button',
      '🔄 counterclockwise arrows refresh',
      '🔃 clockwise vertical arrows',
      '🔊 speaker high volume loud',
      '🔉 speaker medium volume',
      '🔈 speaker low volume',
      '🔇 muted speaker mute',
      '🔴 red circle',
      '🟠 orange circle',
      '🟡 yellow circle',
      '🟢 green circle',
      '🔵 blue circle',
      '🟣 purple circle',
      '🟤 brown circle',
      '⚫ black circle',
      '⚪ white circle',
      '🟥 red square',
      '🟧 orange square',
      '🟨 yellow square',
      '🟩 green square',
      '🟦 blue square',
      '🟪 purple square',
      '🟫 brown square',
      '⬛ black large square',
      '⬜ white large square',
      '◼️ black medium square',
      '◻️ white medium square',
      '◾ black medium small square',
      '◽ white medium small square',
      '▪️ black small square',
      '▫️ white small square',
      '🔶 large orange diamond',
      '🔷 large blue diamond',
      '🔸 small orange diamond',
      '🔹 small blue diamond',
      '🔺 red triangle pointed up',
      '🔻 red triangle pointed down',
      '🔘 radio button',
      '🔳 white square button',
      '🔲 black square button',
      '♠️ spade suit',
      '♥️ heart suit',
      '♦️ diamond suit',
      '♣️ club suit',
      '🃏 joker',
      '🀄 mahjong red dragon',
      '🎴 flower playing cards',
      '♈ aries',
      '♉ taurus',
      '♊ gemini',
      '♋ cancer',
      '♌ leo',
      '♍ virgo',
      '♎ libra',
      '♏ scorpio',
      '♐ sagittarius',
      '♑ capricorn',
      '♒ aquarius',
      '♓ pisces',
      '⛎ ophiuchus',
      '🔯 dotted six pointed star',
      '🕉️ om hindu',
      '🕎 menorah',
      '✡️ star of david',
      '☸️ wheel of dharma',
      '☯️ yin yang',
      '✝️ latin cross',
      '☦️ orthodox cross',
      '☪️ star and crescent islam',
      '☮️ peace symbol',
      '🛐 place of worship',
      '⚛️ atom symbol science',
      '⚜️ fleur de lis',
      '🔱 trident emblem',
      '📛 name badge',
      '🔰 japanese symbol for beginner',
      '⭐ star',
      '🆔 id button',
      '🆘 sos help',
      '🆚 vs versus',
      '🆕 new button',
      '🆓 free button',
      '🆙 up button',
      '🆒 cool button',
      '🆗 ok button',
      '🅰️ a button blood type',
      '🅱️ b button blood type',
      '🆎 ab button blood type',
      '🅾️ o button blood type',
      '🅿️ p button parking',
      '🈳 vacancy',
      '🈂️ service charge',
      '🛗 elevator lift',
      '🚹 mens room',
      '🚺 womens room',
      '🚻 restroom toilet',
      '🚼 baby symbol',
      '🚾 water closet wc',
      '⚧️ transgender symbol',
      '♿ wheelchair symbol accessible',
      '🔤 abc input latin letters',
      '🔡 lowercase input',
      '🔠 uppercase input',
      '🔣 input symbols',
      '🔢 input numbers',
      '0️⃣ keycap zero 0',
      '1️⃣ keycap one 1',
      '2️⃣ keycap two 2',
      '3️⃣ keycap three 3',
      '4️⃣ keycap four 4',
      '5️⃣ keycap five 5',
      '6️⃣ keycap six 6',
      '7️⃣ keycap seven 7',
      '8️⃣ keycap eight 8',
      '9️⃣ keycap nine 9',
      '🔟 keycap ten 10',
      '#️⃣ keycap hash',
      '*️⃣ keycap asterisk star',
      '🕐 one oclock 1:00',
      '🕑 two oclock 2:00',
      '🕒 three oclock 3:00',
      '🕓 four oclock 4:00',
      '🕔 five oclock 5:00',
      '🕕 six oclock 6:00',
      '🕖 seven oclock 7:00',
      '🕗 eight oclock 8:00',
      '🕘 nine oclock 9:00',
      '🕙 ten oclock 10:00',
      '🕚 eleven oclock 11:00',
      '🕛 twelve oclock 12:00',
    ]],

    ['Flags', '🏳️', [
      '🏳️ white flag surrender',
      '🏴 black flag',
      '🏁 chequered flag finish race',
      '🚩 triangular flag',
      '🎌 crossed flags',
      '🏳️‍🌈 rainbow flag pride',
      '🏳️‍⚧️ transgender flag',
      '🏴‍☠️ pirate flag',
      '🇮🇳 india flag',
      '🇺🇸 united states flag usa america',
      '🇬🇧 united kingdom flag uk britain',
      '🇨🇦 canada flag',
      '🇦🇺 australia flag',
      '🇳🇿 new zealand flag',
      '🇮🇪 ireland flag',
      '🇫🇷 france flag',
      '🇩🇪 germany flag',
      '🇮🇹 italy flag',
      '🇪🇸 spain flag',
      '🇵🇹 portugal flag',
      '🇳🇱 netherlands flag',
      '🇧🇪 belgium flag',
      '🇨🇭 switzerland flag',
      '🇦🇹 austria flag',
      '🇸🇪 sweden flag',
      '🇳🇴 norway flag',
      '🇩🇰 denmark flag',
      '🇫🇮 finland flag',
      '🇮🇸 iceland flag',
      '🇵🇱 poland flag',
      '🇨🇿 czechia flag',
      '🇭🇺 hungary flag',
      '🇬🇷 greece flag',
      '🇹🇷 turkey flag',
      '🇷🇺 russia flag',
      '🇺🇦 ukraine flag',
      '🇷🇴 romania flag',
      '🇷🇸 serbia flag',
      '🇭🇷 croatia flag',
      '🇧🇬 bulgaria flag',
      '🇯🇵 japan flag',
      '🇨🇳 china flag',
      '🇰🇷 south korea flag',
      '🇹🇼 taiwan flag',
      '🇭🇰 hong kong flag',
      '🇸🇬 singapore flag',
      '🇲🇾 malaysia flag',
      '🇮🇩 indonesia flag',
      '🇹🇭 thailand flag',
      '🇻🇳 vietnam flag',
      '🇵🇭 philippines flag',
      '🇧🇩 bangladesh flag',
      '🇵🇰 pakistan flag',
      '🇱🇰 sri lanka flag',
      '🇳🇵 nepal flag',
      '🇧🇹 bhutan flag',
      '🇲🇻 maldives flag',
      '🇲🇲 myanmar flag',
      '🇦🇫 afghanistan flag',
      '🇮🇷 iran flag',
      '🇮🇶 iraq flag',
      '🇸🇦 saudi arabia flag',
      '🇦🇪 united arab emirates flag dubai',
      '🇶🇦 qatar flag',
      '🇰🇼 kuwait flag',
      '🇴🇲 oman flag',
      '🇧🇭 bahrain flag',
      '🇮🇱 israel flag',
      '🇯🇴 jordan flag',
      '🇱🇧 lebanon flag',
      '🇪🇬 egypt flag',
      '🇿🇦 south africa flag',
      '🇳🇬 nigeria flag',
      '🇰🇪 kenya flag',
      '🇪🇹 ethiopia flag',
      '🇬🇭 ghana flag',
      '🇹🇿 tanzania flag',
      '🇺🇬 uganda flag',
      '🇲🇦 morocco flag',
      '🇩🇿 algeria flag',
      '🇹🇳 tunisia flag',
      '🇧🇷 brazil flag',
      '🇦🇷 argentina flag',
      '🇨🇱 chile flag',
      '🇨🇴 colombia flag',
      '🇵🇪 peru flag',
      '🇲🇽 mexico flag',
      '🇻🇪 venezuela flag',
      '🇺🇾 uruguay flag',
      '🇪🇨 ecuador flag',
      '🇧🇴 bolivia flag',
      '🇵🇾 paraguay flag',
      '🇨🇺 cuba flag',
      '🇯🇲 jamaica flag',
      '🇵🇦 panama flag',
      '🇨🇷 costa rica flag',
      '🇺🇳 united nations flag',
      '🇪🇺 european union flag',
    ]],
  ];

  /* Parsed once at load rather than on every picker open. The old catalogue was
   * ninety-odd bare strings and could be walked for free; this one is over a
   * thousand entries that each need splitting, and doing that on the tap that
   * opens the panel is the tap that would feel slow. */
  const categories = GROUPS.map(([name, icon, rows]) => ({
    name,
    icon,
    items: rows.map((row) => {
      const gap = row.indexOf(' ');
      return { char: row.slice(0, gap), name: row.slice(gap + 1) };
    }),
  }));

  /* One flat list for search, first-listed name wins.
   *
   * A glyph legitimately appears in two categories — 🐟 is both Reef and
   * Nature, 🎣 is Reef and Objects — and without this a search for "fish"
   * returned the same button twice, which reads as a rendering bug rather than
   * as two categories agreeing. */
  const index = [];
  const seen = new Set();
  categories.forEach((category) => {
    category.items.forEach((item) => {
      if (seen.has(item.char)) return;
      seen.add(item.char);
      index.push(item);
    });
  });

  root.ReefEmoji = { categories, index };
})(self);
